config/routes.rb
Rails.application.routes.draw do
  get 'choose_name' => 'lead_gen#choose_name'
  get 'suggestor' => 'lead_gen#suggestor'
  post 'lead_gen/suggestion_engine' => 'lead_gen#suggestion_engine'
  resources :black_lists
  post 'blacklist_word_imports' => 'black_lists#blacklist_word_imports'
  post 'lead_gen/take_decision' => 'lead_gen#take_decision'
end

app/models/black_list.rb
class BlackList < ActiveRecord::Base

  def self.open_spreadsheet(file)
  	case File.extname(file.original_filename)
      when '.csv' then Roo::CSV.new(file.path)
      when '.xlsx' then Roo::Excelx.new(file.path)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end

  def self.import_from_file(file)		
    spreadsheet = BlackList.open_spreadsheet(file)
    start = 1
      (start..spreadsheet.last_row).each do |i|
      row_data = spreadsheet.row(i)
      blacklist = BlackList.new(:name => row_data[0])
      blacklist.save(:validate => false)
    end
  end

end

app/models/suffix.rb
class Suffix < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	# ********************************************************************************
	# Dont care for this shit too!
		# before_filter :cors_preflight_check
	# after_filter :cors_set_access_control_headers

	# def cors_set_access_control_headers
	# 	headers['Access-Control-Allow-Origin'] = '*'
	# 	headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, DELETE, OPTIONS'
	# 	headers['Access-Control-Allow-Headers'] = 'Origin, Content-Type, Accept, Authorization, Token'
	# 	headers['Access-Control-Max-Age'] = "1728000"
	# end

	# def cors_preflight_check
	# 	if request.method == 'OPTIONS'
	# 		headers['Access-Control-Allow-Origin'] = '*'
	# 		headers['Access-Control-Allow-Methods'] = 'POST, GET, PUT, DELETE, OPTIONS'
	# 		headers['Access-Control-Allow-Headers'] = 'X-Requested-With, X-Prototype-Version, Token'
	# 		headers['Access-Control-Max-Age'] = '1728000'
	# 		render :text => '', :content_type => 'text/plain'
	# 	end
	# end
	# ********************************************************************************

end

app/controllers/black_lists_controller.rb
class BlackListsController < ApplicationController
  before_action :set_black_list, only: [:show, :edit, :update, :destroy]

  # GET /black_lists
  # GET /black_lists.json
  def index
    @black_lists = BlackList.all
  end

  # GET /black_lists/1
  # GET /black_lists/1.json
  def show
  end

  # GET /black_lists/new
  def new
    @black_list = BlackList.new
  end

  # GET /black_lists/1/edit
  def edit
  end

  # POST /black_lists
  # POST /black_lists.json
  def create
    @black_list = BlackList.new(black_list_params)

    respond_to do |format|
      if @black_list.save
        format.html { redirect_to @black_list, notice: 'Black list was successfully created.' }
        format.json { render :show, status: :created, location: @black_list }
      else
        format.html { render :new }
        format.json { render json: @black_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /black_lists/1
  # PATCH/PUT /black_lists/1.json
  def update
    respond_to do |format|
      if @black_list.update(black_list_params)
        format.html { redirect_to @black_list, notice: 'Black list was successfully updated.' }
        format.json { render :show, status: :ok, location: @black_list }
      else
        format.html { render :edit }
        format.json { render json: @black_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /black_lists/1
  # DELETE /black_lists/1.json
  def destroy
    @black_list.destroy
    respond_to do |format|
      format.html { redirect_to black_lists_url, notice: 'Black list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def blacklist_word_imports
    if(params[:file].present?)
      begin
        BlackList.import_from_file(params[:file])
        redirect_to black_lists_path
      rescue
        redirect_to black_lists_path
      end
    else
      redirect_to black_lists_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_black_list
      @black_list = BlackList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def black_list_params
      params.require(:black_list).permit(:name)
    end
end

app/controllers/lead_gen_controller.rb
require 'elasticsearch'

class LeadGenController < ApplicationController
	def choose_name
	end
	def take_decision
		name_approver = NameApprover.new(params["company_name"])
		json_data = name_approver.take_decision
		render :json => json_data
	end

	def suggestor
	end

	def suggestion_engine
		suggestor = Suggestor.new(params["company_name"])
		response = suggestor.check_name
		render :text => response
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/black_lists/_form.html.erb
<%= form_for(@black_list) do |f| %>
  <% if @black_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@black_list.errors.count, "error") %> prohibited this black_list from being saved:</h2>

      <ul>
      <% @black_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/black_lists/edit.html.erb
<h1>Editing Black List</h1>

<%= render 'form' %>

<%= link_to 'Show', @black_list %> |
<%= link_to 'Back', black_lists_path %>

app/views/black_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Black Lists</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @black_lists.each do |black_list| %>
      <tr>
        <td><%= black_list.name %></td>
        <td><%= link_to 'Show', black_list %></td>
        <td><%= link_to 'Edit', edit_black_list_path(black_list) %></td>
        <td><%= link_to 'Destroy', black_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Black list', new_black_list_path %>

<h3>Attach Black List Words</h3>
<%= form_tag blacklist_word_imports_path, multipart: true do %>
  <%= file_field_tag :file %>
  <br>
  <%= submit_tag "Import" ,:class => "black_btn" %>
<% end %>

app/views/black_lists/new.html.erb
<h1>New Black List</h1>

<%= render 'form' %>

<%= link_to 'Back', black_lists_path %>

app/views/black_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @black_list.name %>
</p>

<%= link_to 'Edit', edit_black_list_path(@black_list) %> |
<%= link_to 'Back', black_lists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LeadGenApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lead_gen/choose_name.html.erb
<style>
	.height-fix {
		margin-top: 8px;
	}
</style>

<div class="container-fluid">
	<div class="form-group">

		<div class="row">
			<div class="col-md-6">
				<label>1. Select Industry</label>
				<select class="form-control">
					<option>Legal</option>
					<option>Manufacturing</option>
					<option>Textiles</option>
					<option>Tourism</option>
				</select>
			</div>
		</div>
		<br>

		<div class="row">
			<div class="col-md-6">
				<label>2. Company Objective</label>
				<textarea class="form-control" rows="5"></textarea>
			</div>
		</div>
		<br>

		<div class="row">
			<div class="col-md-6">
				<label>3. Check Company Name Availability</label>
			</div>
		</div>
		<div class="row">
			<div class="col-md-3">
				<input class="form-control" type="text" id="company_name"></input>
			</div>
			<div class="col-md-3">
				<select class="form-control" id="suffix">
					<option>Legal Solutions</option>
					<option>Law Solutions</option>
				</select>
			</div>
			<div class="col-md-3">
				<div class="height-fix"><b>Private Limited</b></div>
			</div>
			<div class="col-md-3">
				<button type="button" class="btn btn-success" id="check">Check</button>
			</div>
		</div>
		<br>

		<div id="results_here"></div>

		<div class="row">
			<div class="col-md-6">
				<label>4. Significance of the name</label>
				<textarea class="form-control" rows="5"></textarea>
			</div>
		</div>
		<br>

		<button type="button" class="btn btn-primary">Submit for Name Approval Process</button>

	</div>
</div>

<!--
Bullshit configuration for enabling CORS in elasticsearch
Add the below stuff in elasticsearch.yml file
*********************************************************
http.cors.allow-origin: "/.*/"
http.cors.enabled: true
discovery.zen.ping.multicast.enabled: false
*********************************************************
-->

<script>

// $(document).ready(function() {
// 	$("#company_name").blur(function() {
// 		getSearchResults($('#company_name').val());
// 	})
// });

// function getSearchResults(search_query) {
//   var data;
//   $.ajax({
//     type: "GET",
//     crossDomain: true,
//     url: 'http://localhost:9200/company/external/_search?q=company_name:' + search_query,
//     dataType: "JSON",
//     success: function(data) {
// 			data = JSON.stringify(data);
// 			document.getElementById('results_here').innerHTML = data;
//     }
//   });
// }

// Modify search results by size
// http://localhost:9200/company/external/_search?size=1000

	$(document).ready(function() {
	  $("#company_name").autocomplete({
	    source: function(request, response) {
	      var wildcard = { "company_name": "*" + request.term.toLowerCase() + "*"};
	      var postData = {
	          "query": { "match_phrase": wildcard },
	          "fields": ["company_name", "_id"]
	      };
	      $.ajax({
	        url: "http://localhost:9200/company/external/_search",
	        type: "POST",
	        dataType: "JSON",
	        data: JSON.stringify(postData),
	        success: function(data) {
	          response($.map(data.hits.hits, function(item) {
	            return {
	              label: item.fields.company_name,
	              id: item.fields._id
	            }
	          }));
	        },
	      });
	    },
	    minLength: 2
	  })
	});

	$(document).ready(function() {
		$("#check").click(function() {
			var name = $("#company_name").val();
			var suffix = $("#suffix :selected").text();;
			var pvt_ltd = "Private Limited";
			company_name = name + " " + suffix + " " + pvt_ltd

			$.ajax({
		    type: "POST",
		    url: 'http://localhost:3000/lead_gen/take_decision',
		    data: { company_name : company_name.toUpperCase() },
		    success: function(data) {
					if(data.hits.total == 0) {
						document.getElementById('results_here').innerHTML = "Company Name is available";
					} else {
						document.getElementById('results_here').innerHTML = "Company Name is not available";
					}
		    }
		  });

		});
	});

</script>

app/views/lead_gen/suggestor.html.erb
<input type="text" id="company_name" />
<button id="check">Check</button>
<br>

<div id="result"></div>

<script>
	
	$(document).ready(function() {
		// Main guy who talks with elasticsearch for decision
		$("#check").click(function() {
			var company_name = $("#company_name").val();
			console.log(company_name);
			$.ajax({
		    type: "POST",
		    url: '/lead_gen/suggestion_engine',
		    data: { company_name : company_name.toUpperCase() },
		    success: function(data) {

		    	console.log(data);
		    	// data.replace("/n", "<br>")
		    	$("#result").html(data.replace(/\n/g, '<br />'));
		    	
		    }
		  });

		});
	});
</script>